### ISSUE TITLE
cmake error: configuring incomplete when building pr_unirender from the main build script

### ISSUE THREAD

**Issue by Peterscraps** [Silverlan/pragma#29]
python 3.9.7 (active)
cmake 3.25.1

seems like the `pr_unirender` modules' ``setup.py`` script at line 25 doesn't catch the double backslashes when it's called by subprocess in the main ``build.py`` script at line 202, which raises an error before it can be corrected like at line 625
```
-- Compiling OpenSubdiv version v3_4_3
-- Using cmake version 3.25.1
-- Could NOT find GLFW (missing: GLFW_INCLUDE_DIR GLFW_LIBRARIES) (Required is at least version "3.0.0")
CMake Error at cmake/FindDXSDK.cmake:84 (message):
  Could not find required library d3d11
Call Stack (most recent call first):
  CMakeLists.txt:377 (find_package)


-- Configuring incomplete, errors occurred!
See also "C:/pragma/pragma/deps/OpenSubdiv/build/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "c:\pragma\pragma\build_scripts\build.py", line 651, in <module>
    execbuildscript(scriptPath)
  File "c:\pragma\pragma\build_scripts\build.py", line 603, in execbuildscript
    execfile(filepath,g,l)
  File "c:\pragma\pragma\build_scripts\build.py", line 525, in execfile
    exec(compile(file.read(), filepath, 'exec'), globals, locals)
  File "c:\pragma\pragma\modules/pr_unirender/build_scripts/setup.py", line 129, in <module>
    cmake_configure("..",generator,["-DTBB_ROOT=" +one_tbb_root,"-DTBB_INCLUDE_DIR=" +one_tbb_root +"/include","-D NO_PTEX=1","-D NO_DOC=1","-D NO_OMP=1","-D NO_TBB=1","-D NO_CUDA=1","-D NO_OPENCL=1","-D NO_CLEW=1","-D NO_EXAMPLES=1"])
  File "c:\pragma\pragma\build_scripts\build.py", line 202, in cmake_configure
    subprocess.run(args,check=True)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cmake', '..', '-G', 'Visual Studio 17 2022', '-DTBB_ROOT=c:\\pragma\\pragma/deps/tbb2019_20190605oss', '-DTBB_INCLUDE_DIR=c:\\pragma\\pragma/deps/tbb2019_20190605oss/include', '-D NO_PTEX=1', '-D NO_DOC=1', '-D NO_OMP=1', '-D NO_TBB=1', '-D NO_CUDA=1', '-D NO_OPENCL=1', '-D NO_CLEW=1', '-D NO_EXAMPLES=1']' returned non-zero exit status 1.
```
Also I don't know if running the script inside an empty folder named pragma would cause any problems, I assume not.
 
Attached: the 'see also' warning log below the error message
[CMakeOutput.log](https://github.com/Silverlan/pragma/files/10430677/CMakeOutput.log)

**Comment by Silverlan** [comment]
Thanks for the report!
This should be fixed now, can you try re-running the build script?

**Comment by Peterscraps** [comment]
It built! cheers
